### ISSUE TITLE
re-join forces

### ISSUE THREAD

**Issue by istr** [attiks/bugsnap#9]
Would be nice if we could merge our efforts into a single version again (e.g. @rysenko [upstream](https://github.com/rysenko/bugsnap)) and make it _the_ free screenshot tool with excellent bug-tracker integration. There are lots of screenshot tools, but most focus on SaaS (so want $$$ for continuous usage and integrate via intermediate webservices), only very few that are strictly local and nearly none with first class issue tracker integration.

**Comment by attiks** [comment]
Great idea, how do you want to handle it?

**Comment by rysenko** [comment]
I think you could just make PR into upstream if you want. I'll review/merge it and deploy new version to Chrome Store.

**Comment by attiks** [comment]
I had a quick look, will need to do a lot of cherry picking, I'll try to find some time tomorrow

**Comment by istr** [comment]
Ok... Apart from "re-branding" cherry picking https://github.com/attiks/bugsnap vs https://github.com/rysenko/bugsnap seems not so very difficult. If @rysenko accepts, cherry picking could be skipped and it could just start with a plain merge attiks/master to rysenko/master. After that some docs and maybe a gh-pages branch should do. I would volunteer to do that and send PR in feature-branches to upstream directly.

**Comment by attiks** [comment]
If you have the time, feel free, I'm a bit busy for the moment
